name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    name: Running on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel 

      - name: Install dependencies
        run: pipenv install --deploy --dev

      - name: Run linter
        run: pipenv run lint
